apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: jenkins
  annotations:
    kubernetes.io/ingress.class: "nginx"    
    cert-manager.io/issuer: "letsencrypt-staging"
spec:
  tls:
  # -- staging ------------------  
  - secretName: results-staging-tls
    hosts:
    - results.staging.llvm-merge-guard.org
  - secretName: results-staging-tls
    hosts:
    - jenkins.staging.llvm-merge-guard.org

  # -- prod ------------------  
  - secretName: results-prod-tls
    hosts:
    - results.llvm-merge-guard.org    
  - secretName: jenkins-prod-tls
    hosts:
    - jenkins.llvm-merge-guard.org    

  rules:
  # -- prod ------------------  
  - host: results.llvm-merge-guard.org
    http:
      paths:
      - backend:
          serviceName: nginx-results
          servicePort: 80
  - host: jenkins.llvm-merge-guard.org
    http:
      paths:
      - backend:
          serviceName: jenkins-ui
          servicePort: 8080

  # -- staging ------------------  
  - host: jenkins.staging.llvm-merge-guard.org
    http:
      paths:
      - backend:
          serviceName: jenkins-ui
          servicePort: 8080
  - host: results.staging.llvm-merge-guard.org
    http:
      paths:
      - backend:
          serviceName: nginx-results
          servicePort: 80
