# This ingress matches ALL requests to nginx.
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress-all
  namespace: buildkite
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "web-static-ip"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: http-auth
    nginx.ingress.kubernetes.io/auth-realm: "LLVM pre-merge checks"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: phabricator-proxy
          servicePort: 8080