apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress-build
  namespace: buildkite
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "web-static-ip"
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: http-auth
    nginx.ingress.kubernetes.io/auth-realm: "LLVM pre-merge checks"
spec:
  tls:
  - secretName: build-prod-tls
    hosts:
    - build.llvm-merge-guard.org
  rules:
  - host: build.llvm-merge-guard.org
    http:
      paths:
      - backend:
          serviceName: phabricator-proxy
          servicePort: 8080